version: '3.8'

services:
    db:
        image: postgres:15-alpine
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: medias_test
            POSTGRES_PASSWORD: medias_test
            POSTGRES_DB: medias_test
        ports:
            - '5432:5432'

    server:
        build:
            context: ./
            dockerfile: Dockerfile.development
        ports:
            - '8008:8008'
        volumes:
            - logs:/app/logs
            - .:/app
        env_file:
            - .env
        depends_on:
            - db
    
volumes:
    postgres-data:
    logs:

